ERPSzakdolgozat/Models/Client.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ERPSzakdolgozat.Models
{
	public class Client : BaseProperties
	{
		[Required]
		public string ClientId { get; set; }

		[Required]
		public string ClientName { get; set; }

		public string Email { get; set; }

		public string Phone { get; set; }

		public string Mobile { get; set; }

		public string ContactName { get; set; }

		public string Country { get; set; }

		public string ZIP { get; set; }

		public string City { get; set; }

		public string Street { get; set; }

		[NotMapped] // this means the field is not mapped into a table-field in the DB
		public string Address {
			get {
				string a = "";
				if (!string.IsNullOrEmpty(Country))
				{
					a += Country + " - ";
				}
				if (!string.IsNullOrEmpty(ZIP))
				{
					a += ZIP + " ";
				}
				if (!string.IsNullOrEmpty(City))
				{
					a += City + ", ";
				}
				if (!string.IsNullOrEmpty(Street))
				{
					a += Street;
				}
				return a;
			}
			set { }
		}

		public string TaxNumber { get; set; }

		public bool Active { get; set; }
	}
}

ERPSzakdolgozat/Controllers/ClientsController.cs
using ERPSzakdolgozat.Helpers;
using ERPSzakdolgozat.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace ERPSzakdolgozat.Controllers
{
	public class ClientsController : MyController
	{
		public ClientsController(ERPDBContext context) : base(context)
		{
			_context = context;
		}

		// GET: Clients
		public async Task<IActionResult> Index(string search, bool active = true)
		{
			IQueryable<Client> clients = _context.Clients.AsNoTracking();

			if (!string.IsNullOrEmpty(search))
			{
				clients = clients.Where(c => c.ClientId.ToLower().Contains(search.ToLower())
					|| c.ClientName.ToLower().Contains(search.ToLower())
					|| c.ContactName.ToLower().Contains(search.ToLower()));
			}
			if (active)
			{
				clients = clients.Where(c => c.Active);
			}

			ViewData["search"] = search;
			ViewData["active"] = active;

			return View(await clients.OrderBy(c => c.ClientName).ToListAsync());
		}

		// GET: Clients/Details/5
		[Authorize(Policy = "Sales")]
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var client = await _context.Clients
				.FirstOrDefaultAsync(m => m.Id == id);
			if (client == null)
			{
				return NotFound();
			}

			return View(client);
		}

		// GET: Clients/Create
		[Authorize(Policy = "Sales")]
		public IActionResult Create()
		{
			Client client = new Client();
			return View(client);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Policy = "Sales")]
		public async Task<IActionResult> Create(Client client)
		{
			if (ModelState.IsValid)
			{
				client.CreatedDate = DateTime.Now;
				client.ModifiedDate = DateTime.Now;
				client.Id = _context.Clients.Max(t => t.Id) + 1;

				_context.Add(client);
				await _context.SaveChangesAsync();

				TempData["Toast"] = Toasts.Created;
				return RedirectToAction(nameof(Index));
			}
			return View(client);
		}

		// GET: Clients/Edit/5
		[Authorize(Policy = "Sales")]
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var client = await _context.Clients.FindAsync(id);
			if (client == null)
			{
				return NotFound();
			}
			return View(client);
		}

		// POST: Clients/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Policy = "Sales")]
		public async Task<IActionResult> Edit(int id, Client client)
		{
			if (id != client.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(client);
					await _context.SaveChangesAsync();

					TempData["Toast"] = Toasts.Saved;
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!ClientExists(client.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(client);
		}

		// GET: Clients/Delete/5
		[Authorize(Policy = "Sales")]
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var client = await _context.Clients
				.FirstOrDefaultAsync(m => m.Id == id);
			if (client == null)
			{
				return NotFound();
			}

			return View(client);
		}

		// POST: Clients/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		[Authorize(Policy = "Sales")]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var client = await _context.Clients.FindAsync(id);
			_context.Clients.Remove(client);
			await _context.SaveChangesAsync();

			TempData["Toast"] = Toasts.Deleted;
			return RedirectToAction(nameof(Index));
		}

		private bool ClientExists(int id)
		{
			return _context.Clients.Any(e => e.Id == id);
		}
	}
}

ERPSzakdolgozat/Views/Clients/Create.cshtml
@model ERPSzakdolgozat.Models.Client

@{
	ViewData["Title"] = "Client - Create";
}

<h2>Create</h2>

<h4>Client</h4>
<hr />
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<form asp-action="Create">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group row">
				<div class="col-md-4">
					<label asp-for="ClientId" class="control-label"></label>
					<span class="text-muted">(required)</span>
					<input asp-for="ClientId" class="form-control" />
					<span asp-validation-for="ClientId" class="text-danger"></span>
				</div>
				<div class="col-md-8">
					<label asp-for="ClientName" class="control-label"></label>
					<span class="text-muted">(required)</span>
					<input asp-for="ClientName" class="form-control" />
					<span asp-validation-for="ClientName" class="text-danger"></span>
				</div>
			</div>
			<div class="form-group">
				<label asp-for="Email" class="control-label"></label>
				<input asp-for="Email" class="form-control" type="email" />
				<span asp-validation-for="Email" class="text-danger"></span>
			</div>
			<div class="form-group row">
				<div class="col-md-6">
					<label asp-for="Phone" class="control-label"></label>
					<input asp-for="Phone" class="form-control" />
					<span asp-validation-for="Phone" class="text-danger"></span>
				</div>
				<div class="col-md-6">
					<label asp-for="Mobile" class="control-label"></label>
					<input asp-for="Mobile" class="form-control" />
					<span asp-validation-for="Mobile" class="text-danger"></span>
				</div>
			</div>
			<div class="form-group">
				<label asp-for="ContactName" class="control-label"></label>
				<input asp-for="ContactName" class="form-control" />
				<span asp-validation-for="ContactName" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Country" class="control-label"></label>
				<input asp-for="Country" class="form-control" />
				<span asp-validation-for="Country" class="text-danger"></span>
			</div>
			<div class="form-group row">
				<div class="col-md-2">
					<label asp-for="ZIP" class="control-label"></label>
					<input asp-for="ZIP" class="form-control" />
					<span asp-validation-for="ZIP" class="text-danger"></span>
				</div>
				<div class="col-md-4">
					<label asp-for="City" class="control-label"></label>
					<input asp-for="City" class="form-control" />
					<span asp-validation-for="City" class="text-danger"></span>
				</div>
				<div class="col-md-6">
					<label asp-for="Street" class="control-label"></label>
					<input asp-for="Street" class="form-control" />
					<span asp-validation-for="Street" class="text-danger"></span>
				</div>
			</div>
			<div class="form-group">
				<label asp-for="TaxNumber" class="control-label"></label>
				<input asp-for="TaxNumber" class="form-control" />
				<span asp-validation-for="TaxNumber" class="text-danger"></span>
			</div>
			<div class="form-group">
				<div class="checkbox">
					<label>
						<input asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
					</label>
				</div>
			</div>

			<input type="hidden" asp-for="CreatedDate" />
			<input type="hidden" asp-for="ModifiedDate" />

			<div class="form-group">
				<a asp-action="Index" class="btn btn-default">Back to List</a>

				<input type="submit" value="Create" class="btn btn-success pull-right" />
			</div>
		</form>
	</div>
</div>

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ERPSzakdolgozat/Views/Clients/Delete.cshtml
@model ERPSzakdolgozat.Models.Client

@{
    ViewData["Title"] = "Client - Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Client</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClientId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ClientId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ClientName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ClientName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ContactName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ContactName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TaxNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TaxNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>
    </dl>
    
	<form asp-action="Delete">
		<input type="hidden" asp-for="Id" />
		<a asp-action="Index" class="btn btn-default">Back to List</a>
		<input type="submit" value="Delete" class="btn btn-danger" />
	</form>
</div>

ERPSzakdolgozat/Views/Clients/Details.cshtml
@model ERPSzakdolgozat.Models.Client

@{
    ViewData["Title"] = "Client - Details";
}

<h2>Details</h2>

<div>
    <h4>Client</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClientId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ClientId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ClientName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ClientName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ContactName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ContactName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TaxNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TaxNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>
    </dl>
</div>
<div>
	<a asp-action="Index" class="btn btn-default">Back to List</a>
	<a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Edit</a>
</div>

ERPSzakdolgozat/Views/Clients/Edit.cshtml
@model ERPSzakdolgozat.Models.Client

@{
    ViewData["Title"] = "Client - Edit";
}

<h2>Edit</h2>

<h4>Client</h4>
<hr />
<div class="row">
    <div class="col-md-8 col-md-offset-2">
		<form asp-action="Edit">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group row">
				<div class="col-md-4">
					<label asp-for="ClientId" class="control-label"></label>
					<input asp-for="ClientId" class="form-control" />
					<span asp-validation-for="ClientId" class="text-danger"></span>
				</div>
				<div class="col-md-8">
					<label asp-for="ClientName" class="control-label"></label>
					<input asp-for="ClientName" class="form-control" />
					<span asp-validation-for="ClientName" class="text-danger"></span>
				</div>
			</div>
			<div class="form-group">
				<label asp-for="Email" class="control-label"></label>
				<input asp-for="Email" class="form-control" type="email" />
				<span asp-validation-for="Email" class="text-danger"></span>
			</div>
			<div class="form-group row">
				<div class="col-md-6">
					<label asp-for="Phone" class="control-label"></label>
					<input asp-for="Phone" class="form-control" />
					<span asp-validation-for="Phone" class="text-danger"></span>
				</div>
				<div class="col-md-6">
					<label asp-for="Mobile" class="control-label"></label>
					<input asp-for="Mobile" class="form-control" />
					<span asp-validation-for="Mobile" class="text-danger"></span>
				</div>
			</div>

			<div class="form-group">
				<label asp-for="ContactName" class="control-label"></label>
				<input asp-for="ContactName" class="form-control" />
				<span asp-validation-for="ContactName" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Country" class="control-label"></label>
				<input asp-for="Country" class="form-control" />
				<span asp-validation-for="Country" class="text-danger"></span>
			</div>
			<div class="form-group row">
				<div class="col-md-2">
					<label asp-for="ZIP" class="control-label"></label>
					<input asp-for="ZIP" class="form-control" />
					<span asp-validation-for="ZIP" class="text-danger"></span>
				</div>
				<div class="col-md-4">
					<label asp-for="City" class="control-label"></label>
					<input asp-for="City" class="form-control" />
					<span asp-validation-for="City" class="text-danger"></span>
				</div>
				<div class="col-md-6">
					<label asp-for="Street" class="control-label"></label>
					<input asp-for="Street" class="form-control" />
					<span asp-validation-for="Street" class="text-danger"></span>
				</div>
			</div>
			<div class="form-group">
				<label asp-for="TaxNumber" class="control-label"></label>
				<input asp-for="TaxNumber" class="form-control" />
				<span asp-validation-for="TaxNumber" class="text-danger"></span>
			</div>
			<div class="form-group">
				<div class="checkbox">
					<label>
						<input asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
					</label>
				</div>
			</div>
			<input type="hidden" asp-for="Id" />
			<input type="hidden" asp-for="CreatedDate" />
			<input type="hidden" asp-for="ModifiedDate" />

			<div class="form-group">
				<a asp-action="Index" class="btn btn-default">Back to List</a>

				<input type="submit" value="Save" class="btn btn-warning pull-right" />
			</div>
		</form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ERPSzakdolgozat/Views/Clients/Index.cshtml
@model IEnumerable<ERPSzakdolgozat.Models.Client>
@using System.Security.Claims

@{
	ViewData["Title"] = "Clients - List";
}

<h2>Clients</h2>

<form asp-controller="Clients" asp-action="Index" method="get" class="form-horizontal">
	<div class="form-group margin-bottom-sm">
		<div class="col-md-5">
			<label class="control-label">
				<strong>Name / Client Id / Contact</strong>
			</label>

			<div class="input-group">
				<input type="text" name="search" class="form-control" value="@(ViewData["search"])" />

				<span class="input-group-btn">
					<button type="submit" class="btn btn-warning">
						<i class="glyphicon glyphicon-search"></i>
					</button>
				</span>
			</div>
		</div>

		<div class="col-md-2 pt-lg">
			<div class="checkbox" style="margin-left:10px">
				<label>
					@Html.CheckBox("active", (bool)ViewData["active"], new { onchange = "$(this.form).submit()" }) Active
				</label>
			</div>
		</div>

		@if (User.HasClaim(ClaimTypes.Role, "Admin") || User.HasClaim(ClaimTypes.Role, "Sales"))
		{
			<a asp-action="Create" class="btn btn-success btn-sm pull-right mt-lg" data-toggle="tooltip" data-placement="top" title="" data-original-title="Create New">
				<i class="glyphicon glyphicon-plus"></i>
			</a>
		}
	</div>
</form>

<table class="table table-hover">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.ClientId)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.ClientName)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Email)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Phone)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Mobile)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.ContactName)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Address)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Active)
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.ClientId)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.ClientName)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Email)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Phone)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Mobile)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.ContactName)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Address)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Active)
				</td>

				<td class="col-md-2 text-right text-nowrap">
					@if (User.HasClaim(ClaimTypes.Role, "Admin") || User.HasClaim(ClaimTypes.Role, "Sales"))
					{
						<a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning btn-sm" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit">
							<i class="glyphicon glyphicon-pencil"></i>
						</a>
						<a asp-action="Details" asp-route-id="@item.Id" class="btn btn-warning btn-sm" data-toggle="tooltip" data-placement="top" title="" data-original-title="Details">
							<i class="glyphicon glyphicon-list"></i>
						</a>
						<a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm" data-toggle="tooltip" data-placement="right" title="" data-original-title="Delete">
							<i class="glyphicon glyphicon-remove"></i>
						</a>
					}
				</td>
			</tr>
		}
	</tbody>
</table>